# Generated by Django 5.0.3 on 2024-03-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='text',
            field=models.CharField(default='asdf;lkj', max_length=100, null=True),
        ),
    ]
